/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.*;
import dto.*;
import dto.LichHoc;
import resoure.type.Message;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.Vector;

/**
 *
 * @author Pero
 */
public class FormLichHoc extends javax.swing.JPanel {

    private GiangVienBLL giangVienBLL = new GiangVienBLL();
    private LichHocBLL lichHocBLL = new LichHocBLL();
    private PhongHocBLL phongHocBLL =new PhongHocBLL();
    private  KhoaHocBLL khoaHocBLL =new KhoaHocBLL();
    private DefaultTableModel renderTimeLineTable=new DefaultTableModel();
    private DefaultTableModel renderCourseTable=new DefaultTableModel();
    private ArrayList<LichHoc> danhSachLichHoc=new ArrayList<>();
    private ArrayList<GiangVien> danhSachGiangVien = new ArrayList<>();
    private ArrayList<PhongHoc> danhSachPhong = new ArrayList<>();
    Hashtable<String, String> giangVienLib = new Hashtable<>();
    Hashtable<String, String> phongHocLib = new Hashtable<>();
    Hashtable<Integer, String> caHocLib =new Hashtable<Integer, String>();
    Hashtable<String, String> giangVienLibReverse = new Hashtable<>();
    Hashtable<String, String> phongHocLibReverse = new Hashtable<>();
    Hashtable<String, Integer> caHocLibReverse =new Hashtable<>();

    /**
     * Creates new form FormLichHoc
     */
    public FormLichHoc() {
        initComponents();
        txtMaKH.setEditable(false);
        loadDanhSachGiangVien();
        loadDanhSachPhong();
        loadDanhSachLichHoc();
        loadDanhSachKhoaHoc();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTimKiem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pnTim = new javax.swing.JPanel();
        btnTim = new javax.swing.JLabel();
        pnTim1 = new javax.swing.JPanel();
        btnTim1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khoahoc = new javax.swing.JTable();
        pnSua = new javax.swing.JPanel();
        btnSua = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnXoa = new javax.swing.JPanel();
        btnXoa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_lichhoc = new javax.swing.JTable();
        cmbGV = new javax.swing.JComboBox<>();
        cmbPhong = new javax.swing.JComboBox<>();
        pnThem1 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbThu = new javax.swing.JComboBox<>();
        cmbCaHoc = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1400, 740));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lịch học");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã KH:");

        txtMaKH.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txtMaKH.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Chọn Phòng :");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ngày học:");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Chọn GV: ");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtTimKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tìm kiếm:");

        pnTim.setBackground(new java.awt.Color(51, 51, 51));
        pnTim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTim.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/search.png"))); // NOI18N
        btnTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search();
            }
        });

        javax.swing.GroupLayout pnTimLayout = new javax.swing.GroupLayout(pnTim);
        pnTim.setLayout(pnTimLayout);
        pnTimLayout.setHorizontalGroup(
            pnTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimLayout.setVerticalGroup(
            pnTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnTim1.setBackground(new java.awt.Color(51, 51, 51));
        pnTim1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTim1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnTim1.setForeground(new java.awt.Color(255, 255, 255));
        btnTim1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTim1.setText("Làm mới");
        btnTim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshField();
                loadDanhSachLichHoc();
            }
        });

        javax.swing.GroupLayout pnTim1Layout = new javax.swing.GroupLayout(pnTim1);
        pnTim1.setLayout(pnTim1Layout);
        pnTim1Layout.setHorizontalGroup(
            pnTim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTim1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTim1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTim1Layout.setVerticalGroup(
            pnTim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTim1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTim1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbl_khoahoc.setBackground(new java.awt.Color(255, 255, 255));
        tbl_khoahoc.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tbl_khoahoc.setForeground(new java.awt.Color(2, 2, 2));
        tbl_khoahoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên khóa học", "Thời Gian Bắt Đầu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_khoahoc.setRowHeight(36);
        tbl_khoahoc.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tbl_khoahoc.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_khoahoc.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                chooseRowKhoaHoc(tbl_khoahoc.getSelectedRow());
            }
        });

        jScrollPane1.setViewportView(tbl_khoahoc);
        if (tbl_khoahoc.getColumnModel().getColumnCount() > 0) {
            tbl_khoahoc.getColumnModel().getColumn(0).setResizable(false);
            tbl_khoahoc.getColumnModel().getColumn(1).setResizable(false);
            tbl_khoahoc.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbl_khoahoc.getColumnModel().getColumn(2).setResizable(false);
            tbl_khoahoc.getColumnModel().getColumn(2).setPreferredWidth(5);

        }

        pnSua.setBackground(new java.awt.Color(220, 128, 37));
        pnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSua.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update();
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/edit.png"))); // NOI18N

        javax.swing.GroupLayout pnSuaLayout = new javax.swing.GroupLayout(pnSua);
        pnSua.setLayout(pnSuaLayout);
        pnSuaLayout.setHorizontalGroup(
            pnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSuaLayout.setVerticalGroup(
            pnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnXoa.setBackground(new java.awt.Color(173, 36, 36));
        pnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnXoa.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoa.setText("Xóa ");
        btnXoa.setToolTipText("");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete();
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/delete.png"))); // NOI18N

        javax.swing.GroupLayout pnXoaLayout = new javax.swing.GroupLayout(pnXoa);
        pnXoa.setLayout(pnXoaLayout);
        pnXoaLayout.setHorizontalGroup(
            pnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnXoaLayout.setVerticalGroup(
            pnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ca học:");

        tbl_lichhoc.setBackground(new java.awt.Color(255, 255, 255));
        tbl_lichhoc.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        tbl_lichhoc.setForeground(new java.awt.Color(2, 2, 2));
        tbl_lichhoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Mã GV", "Mã phòng", "Ngày ", "Ca Học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_lichhoc.setRowHeight(36);
        tbl_lichhoc.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tbl_lichhoc.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_lichhoc.getTableHeader().setReorderingAllowed(false);
        tbl_lichhoc.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                chooseRow(tbl_lichhoc.getSelectedRow());
            }
        });
        jScrollPane2.setViewportView(tbl_lichhoc);
        if (tbl_lichhoc.getColumnModel().getColumnCount() > 0) {
            tbl_lichhoc.getColumnModel().getColumn(0).setResizable(false);
            tbl_lichhoc.getColumnModel().getColumn(1).setResizable(false);
            tbl_lichhoc.getColumnModel().getColumn(2).setResizable(false);
            tbl_lichhoc.getColumnModel().getColumn(3).setResizable(false);
            tbl_lichhoc.getColumnModel().getColumn(4).setResizable(false);
        }

        cmbGV.setEditable(false);
        cmbGV.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N

        cmbPhong.setEditable(false);
        cmbPhong.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N

        pnThem1.setBackground(new java.awt.Color(51, 51, 51));
        pnThem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnThem1.setBackground(new java.awt.Color(8, 130, 44));
        btnThem1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnThem1.setForeground(new java.awt.Color(255, 255, 255));
        btnThem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThem1.setText("Sắp lịch");
        btnThem1.setToolTipText("");
        btnThem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add();
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/calendar.png"))); // NOI18N

        javax.swing.GroupLayout pnThem1Layout = new javax.swing.GroupLayout(pnThem1);
        pnThem1.setLayout(pnThem1Layout);
        pnThem1Layout.setHorizontalGroup(
            pnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnThem1Layout.setVerticalGroup(
            pnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        cmbThu.setEditable(false);
        cmbThu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        cmbThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6" }));

        cmbCaHoc.setEditable(false);
        cmbCaHoc.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        cmbCaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca sáng (7h30 - 9h30)", "Ca chiều (15h30 - 17h30)", "Ca tối (19h30 - 21h30" }));
        caHocLib.put(1, "Ca sáng (7h30 - 9h30)");
        caHocLib.put(2, "Ca chiều (15h30 - 17h30)");
        caHocLib.put(3, "Ca tối (19h30 - 21h30");
        caHocLibReverse.put("Ca sáng (7h30 - 9h30)", 1);
        caHocLibReverse.put("Ca chiều (15h30 - 17h30)", 2);
        caHocLibReverse.put("Ca tối (19h30 - 21h30", 3);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaKH)
                                            .addComponent(cmbGV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbCaHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbThu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTimKiem)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pnTim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(pnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbThu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(pnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnTim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTimKiem))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimMouseClicked

    }//GEN-LAST:event_btnTimMouseClicked

    private void btnTim1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTim1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTim1MouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked

    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked

    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThem1MouseClicked

    public void refreshField() {
        txtTimKiem.setText("");
        cmbCaHoc.setSelectedIndex(0);
        cmbPhong.setSelectedIndex(0);
        cmbThu.setSelectedIndex(0);
        cmbGV.setSelectedIndex(0);
       
    }
    public ArrayList<String> getField() {
        ArrayList<String> tmp = new ArrayList();
        tmp.add(giangVienLibReverse.get(cmbGV.getSelectedItem()));
        tmp.add(txtMaKH.getText());
        tmp.add(phongHocLibReverse.get(cmbPhong.getSelectedItem()));
        tmp.add(String.valueOf(cmbThu.getSelectedItem()));
        tmp.add(String.valueOf(caHocLibReverse.get(cmbCaHoc.getSelectedItem())));
        return tmp;
    }
    public void add () {
        ArrayList<String> data = getField();
        Message m = lichHocBLL.add(data);
        if (m == Message.OK) {
            JOptionPane.showMessageDialog(null,Message.OK.toString());
            loadDanhSachLichHoc();
        } else {
            JOptionPane.showMessageDialog(null, m.toString());
            refreshField();
        }
    }
    public void update () {

        ArrayList<String> data = getField();
        Message m = lichHocBLL.update(data);
        if (m == Message.OK) {
            JOptionPane.showMessageDialog(null,Message.OK.toString());
            loadDanhSachLichHoc();
        } else {
            JOptionPane.showMessageDialog(null, m.toString());
            refreshField();
        }
    }
    private void loadDanhSachKhoaHoc()
    {
        refreshField();
        ArrayList<KhoaHoc> danhSachKhoaHoc=khoaHocBLL.getListNotOpening();
        renderCourseTable= (DefaultTableModel) tbl_khoahoc.getModel();
        renderCourseTable.setNumRows(0);
        for (KhoaHoc index: danhSachKhoaHoc)
        {
            renderCourseTable.addRow(index.parseArrayLite());
        }
        tbl_khoahoc.setModel(renderCourseTable);
    }
    private void loadDanhSachLichHoc()
    {
        refreshField();
        danhSachLichHoc=lichHocBLL.getList();
        renderTimeLineTable= (DefaultTableModel) tbl_lichhoc.getModel();
        renderTimeLineTable.setNumRows(0);
        for (LichHoc index: danhSachLichHoc)
        {
            renderTimeLineTable.addRow(index.parseArray());
        }
        tbl_lichhoc.setModel(renderTimeLineTable);
    }
    private void loadDanhSachGiangVien(){
        giangVienLib.clear();
        giangVienLibReverse.clear();
        ArrayList<String> gvList = new ArrayList<>();
        ArrayList<GiangVien> giangViens = giangVienBLL.getList();
        for (GiangVien index : giangViens) {
            giangVienLib.put(index.getIdGiangVien(), index.getHoGV()+" "+index.getTenGV()+ " - Mã: "+index.getIdGiangVien().substring(0,10)+"..." );
            giangVienLibReverse.put(index.getHoGV()+" "+index.getTenGV()+ " - Mã: "+index.getIdGiangVien().substring(0,10)+"...", index.getIdGiangVien());
            gvList.add(index.getHoGV()+" "+index.getTenGV()+ " - Mã: "+index.getIdGiangVien().substring(0,10)+"...");
        }
        cmbGV.setModel(new DefaultComboBoxModel(gvList.toArray()));

    }
    private void loadDanhSachPhong(){
        phongHocLib.clear();
        phongHocLibReverse.clear();
        ArrayList<String> phList = new ArrayList<>();
        ArrayList<PhongHoc> phongHocs = phongHocBLL.getList();
        for (PhongHoc index : phongHocs) {
            phongHocLib.put(index.getIdPhongHoc(), index.getTenPhongHoc()+" - Mã: "+index.getIdPhongHoc().substring(0,10)+"...");
            phongHocLibReverse.put( index.getTenPhongHoc()+" - Mã: "+index.getIdPhongHoc().substring(0,10)+"...", index.getIdPhongHoc());

            phList.add(index.getTenPhongHoc()+" - Mã: "+index.getIdPhongHoc().substring(0,10)+"...");
        }
        cmbPhong.setModel(new DefaultComboBoxModel(phList.toArray()));

    }
    private void chooseRow(int row)
    {

        tbl_khoahoc.clearSelection();
        Vector temp=new Vector();
        for(int index=0;index<tbl_lichhoc.getColumnCount();index++)
        {
            temp.add(tbl_lichhoc.getValueAt(row,index));
        }
        txtMaKH.setText(""+temp.get(0));
        cmbGV.setSelectedItem(giangVienLib.get(temp.get(1)));
        cmbPhong.setSelectedItem(phongHocLib.get(temp.get(2)));
        cmbThu.setSelectedItem(temp.get(3));
        cmbCaHoc.setSelectedItem(caHocLib.get(temp.get(4)));


    }

    private void chooseRowKhoaHoc(int row)
    {

        tbl_lichhoc.clearSelection();
        Vector temp=new Vector();
        for(int index=0;index<tbl_khoahoc.getColumnCount();index++)
        {
            temp.add(tbl_khoahoc.getValueAt(row,index));
        }
        txtMaKH.setText(""+temp.get(0));




    }
    private void  delete() {
        if (JOptionPane.showConfirmDialog(null, "Bạn có thật sự muốn xóa! Nhấn Yes để xóa"  ,
                "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
            ArrayList<String> arrayList = getField();
            String id = arrayList.get(0);
            String kh = arrayList.get(1);
            String ph = arrayList.get(2);
            Message m = lichHocBLL.remove(id, kh, ph);
            JOptionPane.showMessageDialog(null, m.toString());
            loadDanhSachLichHoc();
        }
    }
    private void search() {
        String qry = txtTimKiem.getText();
        ArrayList<LichHoc> searchList = lichHocBLL.search(qry);
        danhSachLichHoc=searchList;
        renderTimeLineTable= (DefaultTableModel) tbl_lichhoc.getModel();
        renderTimeLineTable.setNumRows(0);
        for (LichHoc index: danhSachLichHoc)
        {
            renderTimeLineTable.addRow(index.parseArray());
        }
        tbl_lichhoc.setModel(renderTimeLineTable);

     }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSua;
    private javax.swing.JLabel btnThem1;
    private javax.swing.JLabel btnTim;
    private javax.swing.JLabel btnTim1;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JComboBox<String> cmbGV;
    private javax.swing.JComboBox<String> cmbPhong;
    private javax.swing.JComboBox<String> cmbThu;
    private javax.swing.JComboBox<String> cmbCaHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_khoahoc;
    private javax.swing.JTable tbl_lichhoc;
    private javax.swing.JPanel pnSua;
    private javax.swing.JPanel pnThem1;
    private javax.swing.JPanel pnTim;
    private javax.swing.JPanel pnTim1;
    private javax.swing.JPanel pnXoa;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
