/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bll.Helpers;
import bll.HocVienBLL;
import bll.SheetExport;
import dto.HocVien;
import resoure.type.Message;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Pero
 */
public class FormSinhVien extends javax.swing.JPanel {

    /**
     * Creates new form FormSinhVien
     */
    private HocVienBLL hocVienBLL=new HocVienBLL();
    private DefaultTableModel renderStudentTable=new DefaultTableModel();
    private ArrayList<HocVien> danhSachHocVien=new ArrayList<>();
    public FormSinhVien() {
        initComponents();
        txtMa.setEnabled(false);
        loadDanhSachHocVien();
        refreshField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        String gt[] = { "Nam", "Nữ" };
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new JLabel();
        txtHoSv = new javax.swing.JTextField();
        jLabel5 = new JLabel();
        cmbLoai = new javax.swing.JComboBox<>(gt);
        jLabel6 = new JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel7 = new JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel17 = new JLabel();
        txtTenSv = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtTimKiem = new javax.swing.JTextField();
        jLabel8 = new JLabel();
        pnTim = new javax.swing.JPanel();
        btnTim = new JLabel();
        pnTim1 = new javax.swing.JPanel();
        btnLamMoi = new JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sinhvien = new javax.swing.JTable();
        pnThem = new javax.swing.JPanel();
        btnThem = new JLabel();
        jLabel11 = new JLabel();
        pnSua = new javax.swing.JPanel();
        btnSua = new JLabel();
        jLabel16 = new JLabel();
        pnXoa = new javax.swing.JPanel();
        btnXoa = new JLabel();
        jLabel1 = new JLabel();
        pnXuatFileExcel = new javax.swing.JPanel();
        btnXuatFileExcel = new JLabel();
        jLabel12 = new JLabel();
        btnNhapExcel = new javax.swing.JPanel();
        btnDangKyMonHoc = new JLabel();
        jLabel23 = new JLabel();
        jLabel9 = new JLabel();
        txtDiaChi = new javax.swing.JTextField();

        setBackground(new Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1400, 740));

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel2.setBackground(new Color(0, 0, 0));
        jLabel2.setFont(new Font("Roboto", 1, 26)); // NOI18N
        jLabel2.setForeground(new Color(0, 0, 0));
        jLabel2.setText("Thông tin sinh viên");

        jLabel3.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setForeground(new Color(0, 0, 0));
        jLabel3.setText("Mã SV:");

        txtMa.setFont(new Font("Roboto", 0, 16)); // NOI18N

        jLabel4.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel4.setForeground(new Color(0, 0, 0));
        jLabel4.setText("Họ SV:");

        txtHoSv.setFont(new Font("Roboto", 0, 16)); // NOI18N

        jLabel5.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel5.setForeground(new Color(0, 0, 0));
        jLabel5.setText("Giới tính:");

        cmbLoai.setEditable(true);
        cmbLoai.setFont(new Font("Roboto", 1, 16)); // NOI18N

        jLabel6.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel6.setForeground(new Color(0, 0, 0));
        jLabel6.setText("SĐT:");

        txtSDT.setFont(new Font("Dialog", 0, 16)); // NOI18N

        jLabel7.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel7.setForeground(new Color(0, 0, 0));
        jLabel7.setText("Ngày sinh:");

        txtNgaySinh.setFont(new Font("Dialog", 0, 16)); // NOI18N

        jLabel17.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel17.setForeground(new Color(0, 0, 0));
        jLabel17.setText("Tên SV:");

        txtTenSv.setFont(new Font("Dialog", 0, 16)); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtTimKiem.setFont(new Font("Dialog", 0, 14)); // NOI18N

        jLabel8.setFont(new Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new Color(0, 0, 0));
        jLabel8.setText("Tìm kiếm:");

        pnTim.setBackground(new Color(51, 51, 51));
        pnTim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTim.setIcon(new javax.swing.ImageIcon("src/main/java/gui/image/search.png")); // NOI18N
        btnTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search();
            }
        });

        javax.swing.GroupLayout pnTimLayout = new javax.swing.GroupLayout(pnTim);
        pnTim.setLayout(pnTimLayout);
        pnTimLayout.setHorizontalGroup(
            pnTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimLayout.setVerticalGroup(
            pnTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnTim1.setBackground(new Color(51, 51, 51));
        pnTim1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLamMoi.setFont(new Font("Dialog", 1, 16)); // NOI18N
        btnLamMoi.setForeground(new Color(255, 255, 255));
        btnLamMoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshField();
                loadDanhSachHocVien();
            }
        });

        javax.swing.GroupLayout pnTim1Layout = new javax.swing.GroupLayout(pnTim1);
        pnTim1.setLayout(pnTim1Layout);
        pnTim1Layout.setHorizontalGroup(
            pnTim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTim1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTim1Layout.setVerticalGroup(
            pnTim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTim1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbl_sinhvien.setBackground(new Color(255, 255, 255));
        tbl_sinhvien.setFont(new Font("Dialog", 1, 16)); // NOI18N
        tbl_sinhvien.setForeground(new Color(2, 2, 2));
        tbl_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ SV", "Tên SV", "Giới tính", "Ngày sinh", "SĐT", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_sinhvien.setRowHeight(36);
        tbl_sinhvien.setSelectionBackground(new Color(153, 153, 255));
        tbl_sinhvien.setSelectionForeground(new Color(0, 0, 0));
        tbl_sinhvien.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_sinhvien);
        if (tbl_sinhvien.getColumnModel().getColumnCount() > 0) {
            tbl_sinhvien.getColumnModel().getColumn(0).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbl_sinhvien.getColumnModel().getColumn(1).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbl_sinhvien.getColumnModel().getColumn(2).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbl_sinhvien.getColumnModel().getColumn(3).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbl_sinhvien.getColumnModel().getColumn(4).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(5).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbl_sinhvien.getColumnModel().getColumn(6).setResizable(false);
            tbl_sinhvien.getColumnModel().getColumn(6).setPreferredWidth(150);
        }
        tbl_sinhvien.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                chooseRow(tbl_sinhvien.getSelectedRow());
            }
        });

        pnThem.setBackground(new Color(4, 110, 57));
        pnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnThem.setBackground(new Color(8, 130, 44));
        btnThem.setFont(new Font("Roboto", 1, 16)); // NOI18N
        btnThem.setForeground(new Color(255, 255, 255));
        btnThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThem.setText("Thêm");
        btnThem.setToolTipText("");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add();
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/add.png"))); // NOI18N

        javax.swing.GroupLayout pnThemLayout = new javax.swing.GroupLayout(pnThem);
        pnThem.setLayout(pnThemLayout);
        pnThemLayout.setHorizontalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnThemLayout.setVerticalGroup(
            pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnSua.setBackground(new Color(220, 128, 37));
        pnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSua.setFont(new Font("Roboto", 1, 16)); // NOI18N
        btnSua.setForeground(new Color(255, 255, 255));
        btnSua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSua.setText("Sửa");
        btnSua.setToolTipText("");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update();
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/edit.png"))); // NOI18N

        javax.swing.GroupLayout pnSuaLayout = new javax.swing.GroupLayout(pnSua);
        pnSua.setLayout(pnSuaLayout);
        pnSuaLayout.setHorizontalGroup(
            pnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnSuaLayout.setVerticalGroup(
            pnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnXoa.setBackground(new Color(173, 36, 36));
        pnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnXoa.setFont(new Font("Roboto", 1, 16)); // NOI18N
        btnXoa.setForeground(new Color(255, 255, 255));
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoa.setText("Xóa ");
        btnXoa.setToolTipText("");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete();
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/delete.png"))); // NOI18N

        javax.swing.GroupLayout pnXoaLayout = new javax.swing.GroupLayout(pnXoa);
        pnXoa.setLayout(pnXoaLayout);
        pnXoaLayout.setHorizontalGroup(
            pnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnXoaLayout.setVerticalGroup(
            pnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnXuatFileExcel.setBackground(new Color(38, 64, 38));
        pnXuatFileExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnXuatFileExcel.setPreferredSize(new java.awt.Dimension(170, 40));

        btnXuatFileExcel.setFont(new Font("Roboto", 1, 16)); // NOI18N
        btnXuatFileExcel.setForeground(new Color(255, 255, 255));
        btnXuatFileExcel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXuatFileExcel.setText("Xuất file Excel");
        btnXuatFileExcel.setToolTipText("");
        btnXuatFileExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportXLS();
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/excel.png"))); // NOI18N

        javax.swing.GroupLayout pnXuatFileExcelLayout = new javax.swing.GroupLayout(pnXuatFileExcel);
        pnXuatFileExcel.setLayout(pnXuatFileExcelLayout);
        pnXuatFileExcelLayout.setHorizontalGroup(
            pnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnXuatFileExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatFileExcel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnXuatFileExcelLayout.setVerticalGroup(
            pnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatFileExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXuatFileExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnNhapExcel.setBackground(new Color(58, 58, 159));
        btnNhapExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDangKyMonHoc.setFont(new Font("Roboto", 1, 18)); // NOI18N
        btnDangKyMonHoc.setForeground(new Color(255, 255, 255));
        btnDangKyMonHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDangKyMonHoc.setText("Đăng ký khóa học");
        btnDangKyMonHoc.setToolTipText("");
        btnDangKyMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupCourse();
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(("src/main/java/gui/image/getin.png"))); // NOI18N

        javax.swing.GroupLayout btnNhapExcelLayout = new javax.swing.GroupLayout(btnNhapExcel);
        btnNhapExcel.setLayout(btnNhapExcelLayout);
        btnNhapExcelLayout.setHorizontalGroup(
            btnNhapExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNhapExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangKyMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnNhapExcelLayout.setVerticalGroup(
            btnNhapExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNhapExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnNhapExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDangKyMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel9.setFont(new Font("Roboto", 1, 16)); // NOI18N
        jLabel9.setForeground(new Color(0, 0, 0));
        jLabel9.setText("Địa chỉ:");

        txtDiaChi.setFont(new Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(txtHoSv))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSv, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnTim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(pnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnXuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNhapExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoSv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbLoai)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgaySinh)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(pnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnTim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimKiem))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnXuatFileExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimMouseClicked

    }//GEN-LAST:event_btnTimMouseClicked

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked

    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked

    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked

    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXuatFileExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatFileExcelMouseClicked

    }//GEN-LAST:event_btnXuatFileExcelMouseClicked

    private void btnDangKyMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKyMonHocMouseClicked

    }//GEN-LAST:event_btnDangKyMonHocMouseClicked

    public void refreshField() {
        txtTimKiem.setText("");
        txtMa.setText(HocVienBLL.generatorKey());
        txtHoSv.setText("");
        txtTenSv.setText("");
        cmbLoai.setSelectedIndex(0);
        txtNgaySinh.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
    }
    public ArrayList<String> getField() {

        ArrayList<String> tmp = new ArrayList();
        tmp.add(txtMa.getText());
        tmp.add(txtHoSv.getText());
        tmp.add(txtTenSv.getText());
        tmp.add(txtDiaChi.getText());
        tmp.add(txtSDT.getText());
        String s = cmbLoai.getSelectedItem().equals("Nam")? "0" : "1";
        tmp.add(s);
        tmp.add(txtNgaySinh.getText());


        return tmp;
    }
    public void add () {

        ArrayList<String> data = getField();

        Message m = hocVienBLL.add(data);
        if (m == Message.OK) {
            JOptionPane.showMessageDialog(null,Message.OK.toString());
            loadDanhSachHocVien();
        } else {
            JOptionPane.showMessageDialog(null, m.toString());
            refreshField();
        }
    }
    public void update () {

        ArrayList<String> data = getField();

        Message m = hocVienBLL.update(data);
        if (m == Message.OK) {
            JOptionPane.showMessageDialog(null,Message.OK.toString());
            loadDanhSachHocVien();
        } else {
            JOptionPane.showMessageDialog(null, m.toString());
            refreshField();
        }
    }
    private void loadDanhSachHocVien()
    {
        refreshField();
        danhSachHocVien=hocVienBLL.getList();
        renderStudentTable= (DefaultTableModel) tbl_sinhvien.getModel();
        renderStudentTable.setNumRows(0);
        for (HocVien index: danhSachHocVien)
        {
            renderStudentTable.addRow(index.parseArray());
        }
        tbl_sinhvien.setModel(renderStudentTable);
    }
    private void chooseRow(int row)
    {
        Vector temp=new Vector();
        for(int index=0;index<tbl_sinhvien.getColumnCount();index++)
        {
            temp.add(tbl_sinhvien.getValueAt(row,index));
        }
        txtMa.setText(""+temp.get(0));
        txtHoSv.setText((String) temp.get(1));
        txtTenSv.setText((String) temp.get(2));
        cmbLoai.setSelectedItem(temp.get(3));
        txtNgaySinh.setText(Helpers.formatDate((Date) temp.get(4)));
        txtSDT.setText(""+ temp.get(5));
        txtDiaChi.setText(""+ temp.get(6));

    }
    private void  delete() {
        if (JOptionPane.showConfirmDialog(null, "Bạn có thật sự muốn xóa! Nhấn Yes để xóa"  ,
                "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
            String id = getField().get(0);
            Message m = hocVienBLL.remove(id);
            JOptionPane.showMessageDialog(null, m.toString());
            loadDanhSachHocVien();
        }
    }
    private void search() {
        String qry = txtTimKiem.getText();
        ArrayList<HocVien> searchList = hocVienBLL.search(qry);
        danhSachHocVien=searchList;
        renderStudentTable= (DefaultTableModel) tbl_sinhvien.getModel();
        renderStudentTable.setNumRows(0);
        for (HocVien index: danhSachHocVien)
        {
            renderStudentTable.addRow(index.parseArray());
        }
        tbl_sinhvien.setModel(renderStudentTable);

    }
    private void signupCourse() {
        int row= tbl_sinhvien.getSelectedRow();
        if(row==-1)
        {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn học viên.");
        } else {
            Vector temp=new Vector();
            for(int i=0;i<renderStudentTable.getColumnCount();i++)
            {
                temp.add(tbl_sinhvien.getValueAt(row,i));
            }
            DlgDKKhoaHoc dlg = new DlgDKKhoaHoc((String) temp.get(0));
            dlg.setVisible(true);
            dlg.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    if (dlg.getMessage() != Message.CLOSE_EVENT) {
                        JOptionPane.showMessageDialog(null, dlg.getMessage().toString());
                    }

                }
            });
        }
    }
    public void exportXLS() {
        Message message = SheetExport.exportHocVien(HocVien.getHeader(), hocVienBLL.getList());
        if (message == Message.OK) {
           JOptionPane.showMessageDialog(null, message.toString());

        } else {
            JOptionPane.showMessageDialog(null, message.toString());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel btnDangKyMonHoc;
    private javax.swing.JPanel btnNhapExcel;
    private JLabel btnSua;
    private JLabel btnThem;
    private JLabel btnTim;
    private JLabel btnLamMoi;
    private JLabel btnXoa;
    private JLabel btnXuatFileExcel;
    private javax.swing.JComboBox<String> cmbLoai;
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel2;
    private JLabel jLabel23;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnSua;
    private javax.swing.JPanel pnThem;
    private javax.swing.JPanel pnTim;
    private javax.swing.JPanel pnTim1;
    private javax.swing.JPanel pnXoa;
    private javax.swing.JPanel pnXuatFileExcel;
    private javax.swing.JTable tbl_sinhvien;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtHoSv;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTenSv;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtDiaChi;
    // End of variables declaration//GEN-END:variables
}
